/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2019-10-25 12:16:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.FTBC_005fFundView;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import vo.ProjectVO;
import vo.GiftVO;
import java.util.List;

public final class Fund_005fProject_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/FTBC_FundView/../FTBC_Common/FTBC_Common.jsp", Long.valueOf(1571020944368L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("vo.GiftVO");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("vo.ProjectVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");

	String pjo_code = null;
	if (request.getParameter("pjo_code") != null) {
		pjo_code = request.getParameter("pjo_code").toString();
	}

	ProjectVO pVO = null;
	if (request.getAttribute("FundingDetail") != null) {
		pVO = (ProjectVO) request.getAttribute("FundingDetail");
	}
	String mem_email = null;
	if (session.getAttribute("mem_email") != null) {
		mem_email = session.getAttribute("mem_email").toString();
	}
	List<Object> rVO = null;
	List<String> gift_code = null;
	List<GiftVO> gop_option = null;
	String payDate = null;
	String giftcode = null;
	int num = 0;
	if (request.getAttribute("FundingGiftDetail") != null) {
		rVO = (List<Object>) request.getAttribute("FundingGiftDetail");
		gift_code = (List<String>) rVO.get(0);
		gop_option = (List<GiftVO>) rVO.get(1);
		payDate = pVO.getFd_deadLine().replaceFirst("-", "년 ");
		payDate = payDate.replaceFirst("-", "월 ");
		payDate = payDate.concat("일"); 
		rVO.get(num);
	}
	String project_code = pVO.getProject_code();
	int project_code_length = project_code.length();
	project_code = project_code.substring(0,project_code_length-1);
	
      out.write("\r\n");
      out.write("\t<!-- 10-23 정원형 funding_project페이지에 선물상세옵션 추가 -->\r\n");
      out.write("\t");

	List<GiftVO> sList =null;
	if(request.getAttribute("sortationSelect")!=null){
		sList =(List<GiftVO>)request.getAttribute("sortationSelect");
	}
	
	
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>FTBC</title>\r\n");
      out.write("<!--=============================================================================================\r\n");
      out.write("\t펀딩 페이지\r\n");
      out.write("\t얼마짜리 펀딩할건지 선택 하는 페이지\r\n");
      out.write("\t날짜:2019-09-20\r\n");
      out.write("================================================================================================  -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js\"></script>   \r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("   src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link href=\"http://netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.css\"\r\n");
      out.write("   rel=\"stylesheet\">\r\n");
      out.write("<script\r\n");
      out.write("   src=\"http://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("   src=\"http://netdna.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.js\"></script>\r\n");
      out.write("<!--  [iíê·¸]  -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css\">\r\n");
      out.write("<!-- include summernote css/js -->\r\n");
      out.write("<link\r\n");
      out.write("   href=\"http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote.css\"\r\n");
      out.write("   rel=\"stylesheet\">\r\n");
      out.write("<script\r\n");
      out.write("   src=\"http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://www.gstatic.com/charts/loader.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--PG  -->\r\n");
      out.write("\r\n");
      out.write("<!-- ì¬ë¨¸ ë¸í¸ë ì¶©ëë¨\r\n");
      out.write(" <script  src=\"http://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js\"></script> -->\r\n");
      out.write("<!-- iaport : PG(Payment Gateway)_ê²°ì  ëí -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdn.iamport.kr/js/iamport.payment-1.1.5.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../FTBC_Common/FTBC_Common.css?WJSN\">\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"../FTBC_FundView/Fund_Project.css?8\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction pay(id,gift_num) {\r\n");
      out.write("\t\t\tvar donation = $(\"#\"+id).val();\r\n");
      out.write("\t\t\tif(gift_num==0){\r\n");
      out.write("\t\t\t\tlocation.href = '/Funding/payFund?gift_code=0&pjo_code=");
      out.print(pVO.getProject_code());
      out.write("&donation='+donation+'';\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tlocation.href = '/Funding/payFund?gift_code='+gift_num+'&pjo_code=");
      out.print(pVO.getProject_code());
      out.write("&donation='+donation+'';\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction fundThis(id) {\r\n");
      out.write("\t\t\t$(\".Fund_Panel\").show();\r\n");
      out.write("\t\t\t$(\"#\" + id).hide();\r\n");
      out.write("\t\t\t$(\".Fund_Panel_Reward\").hide();\r\n");
      out.write("\t\t\t$(\"#\" + id + \"_reward\").show();\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t/*숫자키 누르고 다른거 눌러야 적용됨.  */\r\n");
      out.write("\t\tfunction valueCheck(value, num) {\r\n");
      out.write("\t\t\tvar fundval = Number($(\"#reward_val\" + num).text().replace(\",\", \"\")); //리워드 가격\r\n");
      out.write("\t\t\tvar pvalue = Number(value.replace(\",\", \"\"));\r\n");
      out.write("\t\t\tconsole.log(\"fundval: \" + fundval);\r\n");
      out.write("\t\t\tif (fundval > pvalue) { //입력한 값이 리워드 가격보다  작을경우\r\n");
      out.write("\t\t\t\tconsole.log(\"@\" + fundval + \" : \" + pvalue + \"@\");\r\n");
      out.write("\t\t\t\t$(\"#reward_notice\" + num).text(\"최소 \" + fundval + \"원 이상 입력해주세요\")\r\n");
      out.write("\t\t\t\t$(\"#reward_notice\" + num).css(\"color\", \"#FF0000\");\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$(\"#reward_notice\" + num).text(\"더 많이 입력하실 수 있습니다\")\r\n");
      out.write("\t\t\t\t$(\"#reward_notice\" + num).css(\"color\", \"#4B82F0\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction valStop() {\r\n");
      out.write("\t\t\tevent.stopPropagation();\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t$(\".Fund_Panel_Reward\").hide();\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<div id=\"Fund_ajax\">\r\n");
      out.write("\t\t<div id=\"FundTop_bar\">\r\n");
      out.write("\t\t\t<span id=\"Fund_title\">");
      out.print(pVO.getPjo_longtitle());
      out.write("</span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!--================================================================================================================\r\n");
      out.write("\t \t\t\t\t\t\t\t\t\t\t\t\t[  \t  내용\t]\r\n");
      out.write("\t ================================================================================================================-->\r\n");
      out.write("\t\t\t");

				int giftnum = 0;
			
      out.write("\r\n");
      out.write("\t\t\t<!--------------- 0번  상품----------------->\r\n");
      out.write("\t\t\t<div class=\"row Fund_Panel\" id=\"fund_default");
      out.print(giftnum);
      out.write("\"\r\n");
      out.write("\t\t\t\tonclick=\"fundThis(id)\">\r\n");
      out.write("\t\t\t\t<div class=\"Fund_Header\">\r\n");
      out.write("\t\t\t\t\t<span id=\"reward_val");
      out.print(giftnum);
      out.write("\">1,000</span><span>원 이상\r\n");
      out.write("\t\t\t\t\t\t밀어주시는 분께</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"Fund_Body\">\r\n");
      out.write("\t\t\t\t\t<span>선물을 선택하지 않고, 밀어만 줍니다</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!--------------- 0번  상품 리워드----------------->\r\n");
      out.write("\t\t\t<div class=\"row Fund_Panel_Reward\"\r\n");
      out.write("\t\t\t\tid=\"fund_default");
      out.print(giftnum);
      out.write("_reward\">\r\n");
      out.write("\t\t\t\t<div class=\"Fund_Header\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"fund_valbox\" value=\"1,000\" id=\"gift_reward");
      out.print(giftnum );
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tonkeyup=\"valueCheck(value,'");
      out.print(giftnum);
      out.write("')\" onclick=\"valStop()\"><span>원</span>\r\n");
      out.write("\t\t\t\t\t<a onclick=\"javascript:pay('gift_reward");
      out.print(giftnum );
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(giftnum);
      out.write("')\"><img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"../FTBC_Images/fundbtn.png\"></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"Fund_Body\">\r\n");
      out.write("\t\t\t\t\t<span class=\"reward_notice\" id=\"reward_notice");
      out.print(giftnum);
      out.write("\">더\r\n");
      out.write("\t\t\t\t\t\t많이 입력하실 수 있습니다</span> <br>\r\n");
      out.write("\t\t\t\t\t<span>선물을 선택하지 않고, 밀어만 줍니다</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t");

				for (int i = 0; i < gift_code.size(); i++) {
					giftnum++;
					GiftVO gVO = null;
					for (int k = 0; k < gop_option.size(); k++) {
						if (gift_code.get(i).equals(gop_option.get(k).getGIFT_CODE())) {
							gVO = gop_option.get(k);
							break;
						}
					}
					 if (gVO.GIFT_LIMITED != null) {
                  	  if((Integer.parseInt(gVO.GIFT_LIMITED.toString())) - gVO.getSupport_num()>0){
			
      out.write("\r\n");
      out.write("\t\t\t<!--------------- 한정 수량인데 아직 수량이 남았을 경우----------------->\r\n");
      out.write("\t\t\t<div class=\"row Fund_Panel\" id=\"fund_default");
      out.print(giftnum);
      out.write("\"\r\n");
      out.write("\t\t\t\tonclick=\"fundThis(id)\">\r\n");
      out.write("\t\t\t\t<div class=\"Fund_Header\">\r\n");
      out.write("\t\t\t\t\t<span id=\"reward_val");
      out.print(giftnum);
      out.write('"');
      out.write('>');
      out.print(gVO.getGIFT_UNITMONEY());
      out.write("</span><span>원\r\n");
      out.write("\t\t\t\t\t\t이상 밀어주시는 분께</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"Fund_Body\">\r\n");
      out.write("\t\t\t\t\t");

					String gift_explanation = "";
					if(gVO.getGIFT_EXPLANATION() ==null) {
						gift_explanation = "";
					} else {
						gift_explanation = gVO.getGIFT_EXPLANATION();
					}
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<span>");
      out.print(gift_explanation);
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t");

							for (int j = 0; j < gop_option.size(); j++) {
									if (gop_option.get(j).getGIFT_CODE().equals(gift_code.get(i))) {
										GiftVO kVO = gop_option.get(j);
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li>");
      out.print(kVO.getGOP_OPTION());
      out.write(" (x ");
      out.print(kVO.getGOP_AMMOUNT());
      out.write(")</li>\r\n");
      out.write("\t\t\t\t\t\t\t");
int cnt = 0;
								for(int k=0;k<sList.size();k++){ 
								if(sList.get(k).getGOP_CODE().equals(kVO.getGOP_CODE())){
									if(sList.get(k).getGOD_SORTATION()==0){}
									else if(sList.get(k).getGOD_SORTATION()==1){
										
										if(cnt==0){
											for(int r=0;r<kVO.getGOP_AMMOUNT();r++){
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<select class=\"optionSelect\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
for(int h=0;h<sList.size();h++){
											if(sList.get(h).getGOP_CODE().equals(kVO.getGOP_CODE())&&sList.get(h).getGOD_SORTATION()==1){
												
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option>");
      out.print(sList.get(h).getGOD_DESCRIPTION() );
      out.write("</option>\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");

											}
										} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
  } cnt++;}
									}else if(sList.get(k).getGOD_SORTATION()==2){
										for(int r=0;r<kVO.getGOP_AMMOUNT();r++){
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"optionJugwan\" placeholder=\"");
      out.print(sList.get(k).getGOD_DESCRIPTION() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 	
										}
									}
								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
 
						}
							}
								}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"Fund_Footer\">\r\n");
      out.write("\t\t\t\t\t<span class=\"Footer_num\">");
      out.print(gVO.getSupport_num());
      out.write("</span><span>명이\r\n");
      out.write("\t\t\t\t\t\t선택하였습니다</span> <br>\r\n");
      out.write("\t\t\t\t\t<span>예상 전달일:");
      out.print(gVO.getGIFT_DELIVERYDATE());
      out.write("</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!--------------- 한정 수량인데 아직 수량이 남았을 경우 리워드----------------->\r\n");
      out.write("\t\t\t<div class=\"row Fund_Panel_Reward\"\r\n");
      out.write("\t\t\t\tid=\"fund_default");
      out.print(giftnum);
      out.write("_reward\">\r\n");
      out.write("\t\t\t\t<div class=\"Fund_Header\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"fund_valbox\" id=\"gift_reward");
      out.print(giftnum );
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      out.print(gVO.getGIFT_UNITMONEY());
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tonkeyup=\"valueCheck(value,'");
      out.print(giftnum);
      out.write("')\" onchange=\"valStop()\"><span>원</span>\r\n");
      out.write("\t\t\t\t\t<a onclick=\"javascript:pay('gift_reward");
      out.print(giftnum );
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(gVO.getGIFT_CODE());
      out.write("')\"><img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"../FTBC_Images/fundbtn.png\"></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"Fund_Body\">\r\n");
      out.write("\t\t\t\t\t<span class=\"reward_notice\" id=\"reward_notice");
      out.print(giftnum);
      out.write("\">더\r\n");
      out.write("\t\t\t\t\t\t많이 입력하실 수 있습니다</span> <br>\r\n");
      out.write("\t\t\t\t\t<span>");
      out.print(gVO.getGIFT_EXPLANATION());
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t");
  
						for (int j = 0; j < gop_option.size(); j++) {
									if (gop_option.get(j).getGIFT_CODE().equals(gift_code.get(i))) {
										GiftVO kVO = gop_option.get(j);
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li>");
      out.print(kVO.getGOP_OPTION());
      out.write(" (x ");
      out.print(kVO.getGOP_AMMOUNT());
      out.write(")</li>\r\n");
      out.write("\t\t\t\t\t\t\t");
int cnt = 0;
								for(int k=0;k<sList.size();k++){ 
								if(sList.get(k).getGOP_CODE().equals(kVO.getGOP_CODE())){
									
									if(sList.get(k).getGOD_SORTATION()==0){}
									else if(sList.get(k).getGOD_SORTATION()==1){
										
										if(cnt==0){
											for(int r=0;r<kVO.getGOP_AMMOUNT();r++){
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<select class=\"optionSelect\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
for(int h=0;h<sList.size();h++){
											if(sList.get(h).getGOP_CODE().equals(kVO.getGOP_CODE())&&sList.get(h).getGOD_SORTATION()==1){
												
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option>");
      out.print(sList.get(h).getGOD_DESCRIPTION() );
      out.write("</option>\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");

											}
										} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
  } cnt++;}
									}else if(sList.get(k).getGOD_SORTATION()==2){
										for(int r=0;r<kVO.getGOP_AMMOUNT();r++){
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"optionJugwan\" placeholder=\"");
      out.print(sList.get(k).getGOD_DESCRIPTION() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 	
										}
									}
								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
 
						}
							}
								}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"Fund_Footer\">\r\n");
      out.write("\t\t\t\t\t<span class=\"Footer_num\">");
      out.print(gVO.getSupport_num());
      out.write("</span><span>명이\r\n");
      out.write("\t\t\t\t\t\t선택하였습니다</span> <br>\r\n");
      out.write("\t\t\t\t\t<span>예상 전달일:");
      out.print(gVO.getGIFT_DELIVERYDATE() );
      out.write("</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t");
}else{
				
      out.write("\r\n");
      out.write("\t\t<!---------------------------------------- 한정수량인데 선착순 마감됐을경우.------------------------------>\r\n");
      out.write("\t\t\t<div class=\"row Fund_Panel_magam\" id=\"fund_default");
      out.print(giftnum);
      out.write("\">\r\n");
      out.write("\t\t\t\t<div class=\"Fund_Header\" style=\"opacity:0.4;\">\r\n");
      out.write("\t\t\t\t\t<span id=\"reward_val");
      out.print(giftnum);
      out.write('"');
      out.write('>');
      out.print(gVO.getGIFT_UNITMONEY());
      out.write("</span><span>원\r\n");
      out.write("\t\t\t\t\t\t이상 밀어주시는 분께</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"Fund_Body\" style=\"opacity:0.4;\">\r\n");
      out.write("\t\t\t\t\t");

					String gift_explanation = "";
					if(gVO.getGIFT_EXPLANATION() ==null) {
						gift_explanation = "";
					} else {
						gift_explanation = gVO.getGIFT_EXPLANATION();
					}
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<span>");
      out.print(gift_explanation);
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t");

							for (int j = 0; j < gop_option.size(); j++) {
									if (gop_option.get(j).getGIFT_CODE().equals(gift_code.get(i))) {
										GiftVO kVO = gop_option.get(j);
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li>");
      out.print(kVO.getGOP_OPTION());
      out.write(" (x ");
      out.print(kVO.getGOP_AMMOUNT());
      out.write(")</li>\r\n");
      out.write("\t\t\t\t\t\t\t");
int cnt = 0;
								for(int k=0;k<sList.size();k++){ 
								if(sList.get(k).getGOP_CODE().equals(kVO.getGOP_CODE())){
									if(sList.get(k).getGOD_SORTATION()==0){}
									else if(sList.get(k).getGOD_SORTATION()==1){
										
										if(cnt==0){
											for(int r=0;r<kVO.getGOP_AMMOUNT();r++){
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<select class=\"optionSelect\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
for(int h=0;h<sList.size();h++){
											if(sList.get(h).getGOP_CODE().equals(kVO.getGOP_CODE())&&sList.get(h).getGOD_SORTATION()==1){
												
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option>");
      out.print(sList.get(h).getGOD_DESCRIPTION() );
      out.write("</option>\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");

											}
										} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
  } cnt++;}
									}else if(sList.get(k).getGOD_SORTATION()==2){
										for(int r=0;r<kVO.getGOP_AMMOUNT();r++){
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"optionJugwan\" placeholder=\"");
      out.print(sList.get(k).getGOD_DESCRIPTION() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 	
										}
									}
								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
 
						}
							}
								}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"Fund_Footer\">\r\n");
      out.write("\t\t\t\t\t<span class=\"Footer_num\" style=\"opacity:0.4;\">");
      out.print(gVO.getSupport_num());
      out.write("</span><span style=\"opacity:0.4;\">명이\r\n");
      out.write("\t\t\t\t\t\t선택하였습니다</span> <br>\r\n");
      out.write("\t\t\t\t\t<span style=\"opacity:0.4;\" >예상 전달일:");
      out.print(gVO.getGIFT_DELIVERYDATE());
      out.write("</span><span style=\"color:red;\"><b>&nbsp;&nbsp;&nbsp;선착순 마감 됨!</b></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t");

			}
                  	  }else{
                  		  
      out.write("\r\n");
      out.write("           \t\t\t<!---------------한정 수량이 아닐 경우----------------->\r\n");
      out.write("\t\t\t<div class=\"row Fund_Panel\" id=\"fund_default");
      out.print(giftnum);
      out.write("\"\r\n");
      out.write("\t\t\t\tonclick=\"fundThis(id)\">\r\n");
      out.write("\t\t\t\t<div class=\"Fund_Header\">\r\n");
      out.write("\t\t\t\t\t<span id=\"reward_val");
      out.print(giftnum);
      out.write('"');
      out.write('>');
      out.print(gVO.getGIFT_UNITMONEY());
      out.write("</span><span>원\r\n");
      out.write("\t\t\t\t\t\t이상 밀어주시는 분께</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"Fund_Body\">\r\n");
      out.write("\t\t\t\t\t");

					String gift_explanation = "";
					if(gVO.getGIFT_EXPLANATION() ==null) {
						gift_explanation = "";
					} else {
						gift_explanation = gVO.getGIFT_EXPLANATION();
					}
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<span>");
      out.print(gift_explanation);
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t");

							for (int j = 0; j < gop_option.size(); j++) {
									if (gop_option.get(j).getGIFT_CODE().equals(gift_code.get(i))) {
										GiftVO kVO = gop_option.get(j);
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li>");
      out.print(kVO.getGOP_OPTION());
      out.write(" (x ");
      out.print(kVO.getGOP_AMMOUNT());
      out.write(")</li>\r\n");
      out.write("\t\t\t\t\t\t\t");
int cnt = 0;
								for(int k=0;k<sList.size();k++){ 
								if(sList.get(k).getGOP_CODE().equals(kVO.getGOP_CODE())){
									if(sList.get(k).getGOD_SORTATION()==0){}
									else if(sList.get(k).getGOD_SORTATION()==1){
										
										if(cnt==0){
											for(int r=0;r<kVO.getGOP_AMMOUNT();r++){
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<select class=\"optionSelect\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
for(int h=0;h<sList.size();h++){
											if(sList.get(h).getGOP_CODE().equals(kVO.getGOP_CODE())&&sList.get(h).getGOD_SORTATION()==1){
												
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option>");
      out.print(sList.get(h).getGOD_DESCRIPTION() );
      out.write("</option>\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");

											}
										} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
  } cnt++;}
									}else if(sList.get(k).getGOD_SORTATION()==2){
										for(int r=0;r<kVO.getGOP_AMMOUNT();r++){
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"optionJugwan\" placeholder=\"");
      out.print(sList.get(k).getGOD_DESCRIPTION() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 	
										}
									}
								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
 
						}
							}
								}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"Fund_Footer\">\r\n");
      out.write("\t\t\t\t\t<span class=\"Footer_num\">");
      out.print(gVO.getSupport_num());
      out.write("</span><span>명이\r\n");
      out.write("\t\t\t\t\t\t선택하였습니다</span> <br>\r\n");
      out.write("\t\t\t\t\t<span>예상 전달일:");
      out.print(gVO.getGIFT_DELIVERYDATE());
      out.write("</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!--------------- 한정 수량이 아닐 경우 리워드----------------->\r\n");
      out.write("\t\t\t<div class=\"row Fund_Panel_Reward\"\r\n");
      out.write("\t\t\t\tid=\"fund_default");
      out.print(giftnum);
      out.write("_reward\">\r\n");
      out.write("\t\t\t\t<div class=\"Fund_Header\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"fund_valbox\" id=\"gift_reward");
      out.print(giftnum );
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      out.print(gVO.getGIFT_UNITMONEY());
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tonkeyup=\"valueCheck(value,'");
      out.print(giftnum);
      out.write("')\" onchange=\"valStop()\"><span>원</span>\r\n");
      out.write("\t\t\t\t\t<a onclick=\"javascript:pay('gift_reward");
      out.print(giftnum );
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(gVO.getGIFT_CODE());
      out.write("')\"><img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"../FTBC_Images/fundbtn.png\"></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"Fund_Body\">\r\n");
      out.write("\t\t\t\t\t<span class=\"reward_notice\" id=\"reward_notice");
      out.print(giftnum);
      out.write("\">더\r\n");
      out.write("\t\t\t\t\t\t많이 입력하실 수 있습니다</span> <br>\r\n");
      out.write("\t\t\t\t\t<span>");
      out.print(gVO.getGIFT_EXPLANATION());
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t");
  
						for (int j = 0; j < gop_option.size(); j++) {
									if (gop_option.get(j).getGIFT_CODE().equals(gift_code.get(i))) {
										GiftVO kVO = gop_option.get(j);
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li>");
      out.print(kVO.getGOP_OPTION());
      out.write(" (x ");
      out.print(kVO.getGOP_AMMOUNT());
      out.write(")</li>\r\n");
      out.write("\t\t\t\t\t\t\t");
int cnt = 0;
								for(int k=0;k<sList.size();k++){ 
								if(sList.get(k).getGOP_CODE().equals(kVO.getGOP_CODE())){
									
									if(sList.get(k).getGOD_SORTATION()==0){}
									else if(sList.get(k).getGOD_SORTATION()==1){
										
										if(cnt==0){
											for(int r=0;r<kVO.getGOP_AMMOUNT();r++){
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<select class=\"optionSelect\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
for(int h=0;h<sList.size();h++){
											if(sList.get(h).getGOP_CODE().equals(kVO.getGOP_CODE())&&sList.get(h).getGOD_SORTATION()==1){
												
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option>");
      out.print(sList.get(h).getGOD_DESCRIPTION() );
      out.write("</option>\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");

											}
										} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
  } cnt++;}
									}else if(sList.get(k).getGOD_SORTATION()==2){
										for(int r=0;r<kVO.getGOP_AMMOUNT();r++){
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"optionJugwan\" placeholder=\"");
      out.print(sList.get(k).getGOD_DESCRIPTION() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 	
										}
									}
								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
 
						}
							}
								}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"Fund_Footer\">\r\n");
      out.write("\t\t\t\t\t<span class=\"Footer_num\">");
      out.print(gVO.getSupport_num());
      out.write("</span><span>명이\r\n");
      out.write("\t\t\t\t\t\t선택하였습니다</span> <br>\r\n");
      out.write("\t\t\t\t\t<span>예상 전달일:");
      out.print(gVO.getGIFT_DELIVERYDATE() );
      out.write("</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>       \t\t  \r\n");
      out.write("                  \t\t  ");

                  	  }
					}
				
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
